// {<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf-autotable/3.5.25/jspdf.plugin.autotable.min.js"></script> */}
//     <script>
//     document.getElementById('generatePdf').addEventListener('click', function () {
//     console.log('Generate PDF button clicked'); // Debugging log

//     const confirmGenerate = confirm('Are you sure you want to generate the sales report?');
//     if (!confirmGenerate) {
//         console.log('User canceled PDF generation'); // Debugging log
//         return; // Exit if the user cancels
//     }

//     console.log('Proceeding with PDF generation'); // Debugging log
//     const { jsPDF } = window.jspdf;
//     const doc = new jsPDF();

//     // Add logo
//     const logo = new Image();
//     logo.src = 'assets/navbar-logo1.png'; // Replace with your logo path
//     logo.onload = () => {
//         console.log('Logo loaded successfully'); // Debugging log
//         const logoWidth = 30;
//         const logoHeight = 30;
//         const logoX = 10;
//         const logoY = 10;

//         doc.addImage(logo, 'PNG', logoX, logoY, logoWidth, logoHeight);
//         doc.setFontSize(16);
//         doc.setFont('helvetica', 'bold');
//         doc.text('SMJ Furnishings Philippines Inc', logoX + logoWidth + 5, logoY + 10);
//         doc.setFontSize(10);
//         doc.setFont('helvetica', 'normal');
//         doc.text('1234 Main Street, Makati City, Philippines', logoX + logoWidth + 5, logoY + 20);

//         generatePDFContent();
//     };

//     logo.onerror = () => {
//         console.log('Failed to load logo'); // Debugging log
//         generatePDFContent();
//     };

//     function generatePDFContent() {
//         console.log('Generating PDF content'); // Debugging log
//         doc.setFontSize(18);
//         doc.text('Sales Report', 105, 50, { align: 'center' });
//         doc.setFontSize(12);
//         doc.text('Month: <?= $selected_month ?>', 105, 60, { align: 'center' });
//         doc.setFontSize(10);
//         doc.text('Generated by: <?= $_SESSION["firstname"] . " " . $_SESSION["middlename"] . " " . $_SESSION["surname"] ?>', 10, 70);

//         const table = document.getElementById('salesTable');
//         const headers = Array.from(table.querySelectorAll('thead th')).map(th => th.innerText);
//         const rows = Array.from(table.querySelectorAll('tbody tr')).map(tr => {
//             return Array.from(tr.querySelectorAll('td')).map((td, i) => {
//                 let content = td.innerText;
//                 if (i === 6) {
//                     content = `₱${content.replace(/[^0-9.]/g, '')}`;
//                 }
//                 return content;
//             });
//         });

//         doc.autoTable({
//             head: [headers],
//             body: rows,
//             startY: 80,
//             theme: 'grid',
//             headStyles: { fillColor: [0, 0, 0], textColor: 255, fontStyle: 'bold' },
//             styles: { font: 'helvetica', fontSize: 9, cellPadding: 2, overflow: 'linebreak' },
//             columnStyles: {
//                 0: { cellWidth: 22 },
//                 1: { cellWidth: 25 },
//                 2: { cellWidth: 35 },
//                 3: { cellWidth: 35 },
//                 4: { cellWidth: 35 },
//                 5: { cellWidth: 20 },
//                 6: { cellWidth: 25, halign: 'right' },
//                 7: { cellWidth: 20 },
//                 8: { cellWidth: 20 },
//                 9: { cellWidth: 20 },
//                 10: { cellWidth: 25 },
//             }
//         });

//         const finalY = doc.lastAutoTable.finalY + 10;
//         doc.setFontSize(12);
//         doc.setFont('helvetica', 'bold');
//         doc.text(`Total Sales: ₱<?= number_format($total_sales, 2) ?>`, 105, finalY, { align: 'center' });

//         console.log('Saving PDF'); // Debugging log
//         doc.save('sales_report.pdf');
//     }
// });
//     </script>